# require_relative "../lib"
bruno = User.create(name: "Bruno", age: 5, employed: false)
deep = User.create(name: "Deep", age: 12, employed: false)
max = User.create(name: "Max", age: 17, employed: false)
austin = User.create(name: "Austin", age: 29, employed: false)
leeza = User.create(name: "Leeza", age: 8, employed: false)
jerry = User.create(name: "Jerry", age: 37, employed: false)
justin = User.create(name: "Justin", age: 25, employed:false)
julio = User.create(name: "Julio", age: 34, employed: true)
kyle = User.create(name: "Kyle", age: 44, employed: true)
ryan = User.create(name: "Ryan", age: 70, employed: true)
mor = User.create(name: "Mor", age: 16, employed: true)
jp = User.create(name: "Jp", age: 32, employed: true)
niky = User.create(name: "Niky", age: 34, employed: true)
andrew = User.create(name: "Andrew", age: 66, employed: true)
rob = User.create(name: "Rob", age: 78, employed: true)

wow = Game.create(title: "World of Warcraft", genre: "MMORPG", console: "PC")
pubg_pc = Game.create(title: "Playerunknown's Battleground", genre: "Action", console: "PC")
pubg_ps = Game.create(title: "Playerunknown's Battleground", genre: "Action", console: "Playstation 4")
pubg_xbx = Game.create(title: "Playerunknown's Battleground", genre: "Action", console: "Xbox One")
fortnite_pc = Game.create(title: "Fortnite" , genre: "Action", console: "PC")
fortnite_ps = Game.create(title: "Fortnite" , genre: "Action", console: "Playstation 4")
fortnite_xbx = Game.create(title: "Fortnite" , genre: "Action", console: "Xbox One")
overwatch_pc = Game.create(title: "Overwatch" , genre: "Action", console: "PC")
overwatch_ps = Game.create(title: "Overwatch" , genre: "Action", console: "Playstation 4")
overwatch_xbx = Game.create(title: "Overwatch" , genre: "Action", console: "Xbox One")
madden_ps = Game.create(title: "Madden 2018" , genre: "Sports", console: "Playstation 4")
madden_xbx = Game.create(title: "Madden 2018" , genre: "Sports", console: "Xbox One")
madden_nin = Game.create(title: "Madden 2018" , genre: "Sports", console: "Nintendo")
nba_ps = Game.create(title: "Nba 2k18" , genre: "Sports", console: "Playstation 4")
nba_xbx = Game.create(title: "Nba 2k18" , genre: "Sports", console: "Xbox One")
nba_nin = Game.create(title: "Nba 2k18" , genre: "Sports", console: "Nintendo")
fifa_ps = Game.create(title: "Fifa 2018" , genre: "Sports", console: "Playstation 4")
fifa_xbx = Game.create(title: "Fifa 2018" , genre: "Sports", console: "Xbox One")
fifa_nin = Game.create(title: "Fifa 2018" , genre: "Sports", console: "Nintendo")
hellokitty_pc = Game.create(title: "Hello Kitty Island Adventure" , genre: "MMORPG", console: "PC")
hellokitty_ps = Game.create(title: "Hello Kitty Island Adventure" , genre: "MMORPG", console: "Playstation 4")
hellokitty_xbx = Game.create(title: "Hello Kitty Island Adventure" , genre: "MMORPG", console: "Xbox One")
hellokitty_nin = Game.create(title: "Hello Kitty Island Adventure" , genre: "MMORPG", console: "Ninetendo")
cod_pc = Game.create(title: "Call of Duty MW2" , genre: "Action", console: "PC")
cod_ps = Game.create(title: "Call of Duty MW2" , genre: "Action", console: "Playstation 4")
cod_xbx = Game.create(title: "Call of Duty MW2" , genre: "Action", console: "Xbox One")
cod_nin = Game.create(title: "Call of Duty MW2" , genre: "Action", console: "Nintendo")

GameUser.create(user_id: 7, game_id: )
GameUser.create(user_id: 8, game_id:3 )
GameUser.create(user_id: 9, game_id:4 )
GameUser.create(user_id: 10, game_id:5 )
GameUser.create(user_id: 11, game_id:2 )
GameUser.create(user_id: 12, game_id:8 )
GameUser.create(user_id: 13, game_id:7 )

GameUser.create(game_id: 1, user_id: 1)
GameUser.create(game_id: 2, user_id: 1)
GameUser.create(game_id: 1, user_id: 3)
GameUser.create(game_id: 12, user_id: 4)
GameUser.create(game_id: 6, user_id: 5)
GameUser.create(game_id: 11, user_id: 6)
GameUser.create(game_id: 25, user_id: 4)
GameUser.create(game_id: 20, user_id: 2)
GameUser.create(game_id: 22, user_id: 2)
GameUser.create(game_id: 14, user_id: 3)
GameUser.create(game_id: 3, user_id: 6)
GameUser.create(game_id: 1, user_id: 1)
GameUser.create(game_id: 1, user_id: 4)
GameUser.create(game_id: 2, user_id: 5)
GameUser.create(game_id: 22, user_id: 1)
