# require_relative "../lib"
# Users
bruno = User.create(name: "Bruno", age: 5, employed: false)
deep = User.create(name: "Deep", age: 12, employed: false)
max = User.create(name: "Max", age: 17, employed: false)
austin = User.create(name: "Austin", age: 29, employed: false)
leeza = User.create(name: "Leeza", age: 8, employed: false)
jerry = User.create(name: "Jerry", age: 37, employed: false)
justin = User.create(name: "Justin", age: 25, employed:false)
julio = User.create(name: "Julio", age: 34, employed: true)
kyle = User.create(name: "Kyle", age: 44, employed: true)
ryan = User.create(name: "Ryan", age: 70, employed: true)
mor = User.create(name: "Mor", age: 16, employed: true)
jp = User.create(name: "Jp", age: 32, employed: true)
niky = User.create(name: "Niky", age: 34, employed: true)
andrew = User.create(name: "Andrew", age: 66, employed: true)
rob = User.create(name: "Rob", age: 78, employed: true)

#Games
wow = Game.create(title: "World of Warcraft", genre: "MMORPG", console: "PC")
pubg_pc = Game.create(title: "Playerunknown's Battleground", genre: "Action", console: "PC")
pubg_ps = Game.create(title: "Playerunknown's Battleground", genre: "Action", console: "Playstation 4")
pubg_xbx = Game.create(title: "Playerunknown's Battleground", genre: "Action", console: "Xbox One")
fortnite_pc = Game.create(title: "Fortnite" , genre: "Action", console: "PC")
fortnite_ps = Game.create(title: "Fortnite" , genre: "Action", console: "Playstation 4")
fortnite_xbx = Game.create(title: "Fortnite" , genre: "Action", console: "Xbox One")
overwatch_pc = Game.create(title: "Overwatch" , genre: "Action", console: "PC")
overwatch_ps = Game.create(title: "Overwatch" , genre: "Action", console: "Playstation 4")
overwatch_xbx = Game.create(title: "Overwatch" , genre: "Action", console: "Xbox One")
madden_ps = Game.create(title: "Madden 2018" , genre: "Sports", console: "Playstation 4")
madden_xbx = Game.create(title: "Madden 2018" , genre: "Sports", console: "Xbox One")
madden_nin = Game.create(title: "Madden 2018" , genre: "Sports", console: "Nintendo")
nba_ps = Game.create(title: "Nba 2k18" , genre: "Sports", console: "Playstation 4")
nba_xbx = Game.create(title: "Nba 2k18" , genre: "Sports", console: "Xbox One")
nba_nin = Game.create(title: "Nba 2k18" , genre: "Sports", console: "Nintendo")
fifa_ps = Game.create(title: "Fifa 2018" , genre: "Sports", console: "Playstation 4")
fifa_xbx = Game.create(title: "Fifa 2018" , genre: "Sports", console: "Xbox One")
fifa_nin = Game.create(title: "Fifa 2018" , genre: "Sports", console: "Nintendo")
hellokitty_pc = Game.create(title: "Hello Kitty Island Adventure" , genre: "MMORPG", console: "PC")
hellokitty_ps = Game.create(title: "Hello Kitty Island Adventure" , genre: "MMORPG", console: "Playstation 4")
hellokitty_xbx = Game.create(title: "Hello Kitty Island Adventure" , genre: "MMORPG", console: "Xbox One")
hellokitty_nin = Game.create(title: "Hello Kitty Island Adventure" , genre: "MMORPG", console: "Nintendo")
cod_pc = Game.create(title: "Call of Duty MW2" , genre: "Action", console: "PC")
cod_ps = Game.create(title: "Call of Duty MW2" , genre: "Action", console: "Playstation 4")
cod_xbx = Game.create(title: "Call of Duty MW2" , genre: "Action", console: "Xbox One")
cod_nin = Game.create(title: "Call of Duty MW2" , genre: "Action", console: "Nintendo")
csgo = Game.create(title: "Counter Strike",genre : "Action", console: "PC")
ac_pc = Game.create(title: "Assassins Creed", genre: "Action", console: "PC")
ac_ps = Game.create(title: "Assassins Creed", genre: "Action", console: "Playstation 4")
ac_xbx = Game.create(title: "Assassins Creed", genre: "Action", console: "Xbox One")
ac_nin = Game.create(title: "Assassins Creed", genre: "Action", console: "Nintendo")
sw_pc = Game.create(title: "Star Wars Battlefront" , genre: "Action", console: "PC")
sw_ps = Game.create(title: "Star Wars Battlefront" , genre: "Action", console: "Playstation 4")
sw_xbx = Game.create(title: "Star Wars Battlefront" , genre: "Action", console: "Xbox One")
sw_nin = Game.create(title: "Star Wars Battlefront" , genre: "Action", console: "Nintendo")
skyrim_pc = Game.create(title: "Skyrim" , genre: "MMORPG", console: "PC")
skyrim_ps = Game.create(title: "Skyrim" , genre: "MMORPG", console: "Playstation 4")
skyrim_xbx = Game.create(title: "Skyrim" , genre: "MMORPG", console: "Xbox One")
skyrim_nin = Game.create(title: "Skyrim" , genre: "MMORPG", console: "Nintendo")
gta_pc = Game.create(title: "Grand Theft Auto" , genre: "Action", console: "PC")
gta_ps = Game.create(title: "Grand Theft Auto" , genre: "Action", console: "Playstation 4")
gta_xbx = Game.create(title: "Grand Theft Auto" , genre: "Action", console: "Xbox One")
gta_nin = Game.create(title: "Grand Theft Auto" , genre: "Action", console: "Nintendo")
mk_ps = Game.create(title: "Mortal Kombat" , genre: "Action", console: "Playstation 4")
mk_xbx = Game.create(title: "Mortal Kombat" , genre: "Action", console: "Xbox One")
mk_nin = Game.create(title: "Mortal Kombat" , genre: "Action", console: "Nintendo")
bf_pc = Game.create(title: "Battlefield" , genre: "Action", console: "PC")
bf_ps = Game.create(title: "Battlefield" , genre: "Action", console: "Playstation 4")
bf_xbx = Game.create(title: "Battlefield" , genre: "Action", console: "Xbox One")
bf_nin = Game.create(title: "Battlefield" , genre: "Action", console: "Nintendo")
pikmin_pc = Game.create(title: "Pikmin" , genre: "Action", console: "PC")
pikmin_ps = Game.create(title: "Pikmin" , genre: "Action", console: "Playstation 4")
pikmin_xbx = Game.create(title: "Pikmin" , genre: "Action", console: "Xbox One")
pikmin_nin = Game.create(title: "Pikmin" , genre: "Action", console: "Nintendo")
dm_pc = Game.create(title: "DOOM" , genre: "Action", console: "PC")
dm_ps = Game.create(title: "DOOM" , genre: "Action", console: "Playstation 4")
dm_xbx = Game.create(title: "DOOM" , genre: "Action", console: "Xbox One")
dm_nin = Game.create(title: "DOOM" , genre: "Action", console: "Nintendo")

# Ids
GameUser.create(game_id: 1, user_id: 1)
GameUser.create(game_id: 53, user_id: 1)
GameUser.create(game_id: 2, user_id: 1)
GameUser.create(game_id: 52, user_id: 1)
GameUser.create(game_id: 3, user_id: 1)
GameUser.create(game_id: 4, user_id: 2)
GameUser.create(game_id: 51, user_id: 2)
GameUser.create(game_id: 5, user_id: 2)
GameUser.create(game_id: 50, user_id: 2)
GameUser.create(game_id: 6, user_id: 2)
GameUser.create(game_id: 49, user_id: 3)
GameUser.create(game_id: 7, user_id: 3)
GameUser.create(game_id: 48, user_id: 3)
GameUser.create(game_id: 8, user_id: 3)
GameUser.create(game_id: 47, user_id: 3)
GameUser.create(game_id: 9, user_id: 4)
GameUser.create(game_id: 46, user_id: 4)
GameUser.create(game_id: 10, user_id: 4)
GameUser.create(game_id: 45, user_id: 4)
GameUser.create(game_id: 11, user_id: 4)
GameUser.create(game_id: 44, user_id: 5)
GameUser.create(game_id: 12, user_id: 5)
GameUser.create(game_id: 43, user_id: 5)
GameUser.create(game_id: 13, user_id: 5)
GameUser.create(game_id: 42, user_id: 5)
GameUser.create(game_id: 14, user_id: 6)
GameUser.create(game_id: 41, user_id: 6)
GameUser.create(game_id: 15, user_id: 6)
GameUser.create(game_id: 40, user_id: 6)
GameUser.create(game_id: 16, user_id: 6)
GameUser.create(game_id: 39, user_id: 7)
GameUser.create(game_id: 17, user_id: 7)
GameUser.create(game_id: 38, user_id: 7)
GameUser.create(game_id: 18, user_id: 7)
GameUser.create(game_id: 37, user_id: 7)
GameUser.create(game_id: 19, user_id: 8)
GameUser.create(game_id: 36, user_id: 8)
GameUser.create(game_id: 20, user_id: 8)
GameUser.create(game_id: 35, user_id: 8)
GameUser.create(game_id: 21, user_id: 8)
GameUser.create(game_id: 34, user_id: 9)
GameUser.create(game_id: 22, user_id: 9)
GameUser.create(game_id: 33, user_id: 9)
GameUser.create(game_id: 23, user_id: 9)
GameUser.create(game_id: 32, user_id: 9)
GameUser.create(game_id: 24, user_id: 10)
GameUser.create(game_id: 31, user_id: 10)
GameUser.create(game_id: 25, user_id: 10)
GameUser.create(game_id: 30, user_id: 10)
GameUser.create(game_id: 26, user_id: 10)
GameUser.create(game_id: 29, user_id: 11)
GameUser.create(game_id: 27, user_id: 11)
GameUser.create(game_id: 28, user_id: 11)
GameUser.create(game_id: 1, user_id: 11)
GameUser.create(game_id: 53, user_id: 11)
GameUser.create(game_id: 2, user_id: 12)
GameUser.create(game_id: 52, user_id: 12)
GameUser.create(game_id: 3, user_id: 12)
GameUser.create(game_id: 51, user_id: 12)
GameUser.create(game_id: 4, user_id: 12)
GameUser.create(game_id: 50, user_id: 13)
GameUser.create(game_id: 5, user_id: 13)
GameUser.create(game_id: 49, user_id: 13)
GameUser.create(game_id: 6, user_id: 13)
GameUser.create(game_id: 48, user_id: 13)
GameUser.create(game_id: 7, user_id: 14)
GameUser.create(game_id: 47, user_id: 14)
GameUser.create(game_id: 8, user_id: 14)
GameUser.create(game_id: 46, user_id: 14)
GameUser.create(game_id: 9, user_id: 14)
GameUser.create(game_id: 45, user_id: 15)
GameUser.create(game_id: 10, user_id: 15)
GameUser.create(game_id: 44, user_id: 15)
GameUser.create(game_id: 11, user_id: 15)
GameUser.create(game_id: 43, user_id: 15)
GameUser.create(game_id: 1, user_id: 15)
GameUser.create(game_id: 53, user_id: 15)
GameUser.create(game_id: 2, user_id: 15)
GameUser.create(game_id: 52, user_id: 15)
GameUser.create(game_id: 3, user_id: 15)
GameUser.create(game_id: 4, user_id: 14)
GameUser.create(game_id: 51, user_id: 14)
GameUser.create(game_id: 5, user_id: 14)
GameUser.create(game_id: 50, user_id: 14)
GameUser.create(game_id: 6, user_id: 14)
GameUser.create(game_id: 49, user_id: 13)
GameUser.create(game_id: 7, user_id: 13)
GameUser.create(game_id: 48, user_id: 13)
GameUser.create(game_id: 8, user_id: 13)
GameUser.create(game_id: 47, user_id: 13)
GameUser.create(game_id: 9, user_id: 12)
GameUser.create(game_id: 46, user_id: 12)
GameUser.create(game_id: 10, user_id: 12)
GameUser.create(game_id: 45, user_id: 12)
GameUser.create(game_id: 11, user_id: 12)
GameUser.create(game_id: 44, user_id: 11)
GameUser.create(game_id: 12, user_id: 11)
GameUser.create(game_id: 43, user_id: 11)
GameUser.create(game_id: 13, user_id: 11)
GameUser.create(game_id: 42, user_id: 11)
GameUser.create(game_id: 14, user_id: 10)
GameUser.create(game_id: 41, user_id: 10)
GameUser.create(game_id: 15, user_id: 10)
GameUser.create(game_id: 40, user_id: 10)
GameUser.create(game_id: 16, user_id: 10)
GameUser.create(game_id: 39, user_id: 9)
GameUser.create(game_id: 17, user_id: 9)
GameUser.create(game_id: 38, user_id: 9)
GameUser.create(game_id: 18, user_id: 9)
GameUser.create(game_id: 37, user_id: 9)
GameUser.create(game_id: 19, user_id: 8)
GameUser.create(game_id: 36, user_id: 8)
GameUser.create(game_id: 20, user_id: 8)
GameUser.create(game_id: 35, user_id: 8)
GameUser.create(game_id: 21, user_id: 8)
GameUser.create(game_id: 34, user_id: 7)
GameUser.create(game_id: 22, user_id: 7)
GameUser.create(game_id: 33, user_id: 7)
GameUser.create(game_id: 23, user_id: 7)
GameUser.create(game_id: 32, user_id: 7)
GameUser.create(game_id: 24, user_id: 6)
GameUser.create(game_id: 31, user_id: 6)
GameUser.create(game_id: 25, user_id: 6)
GameUser.create(game_id: 30, user_id: 6)
GameUser.create(game_id: 26, user_id: 6)
GameUser.create(game_id: 29, user_id: 5)
GameUser.create(game_id: 27, user_id: 5)
GameUser.create(game_id: 28, user_id: 5)
GameUser.create(game_id: 1, user_id: 5)
GameUser.create(game_id: 53, user_id: 5)
GameUser.create(game_id: 2, user_id: 4)
GameUser.create(game_id: 52, user_id: 4)
GameUser.create(game_id: 3, user_id: 4)
GameUser.create(game_id: 51, user_id: 4)
GameUser.create(game_id: 4, user_id: 4)
GameUser.create(game_id: 50, user_id: 3)
GameUser.create(game_id: 5, user_id: 3)
GameUser.create(game_id: 49, user_id: 3)
GameUser.create(game_id: 6, user_id: 3)
GameUser.create(game_id: 48, user_id: 3)
GameUser.create(game_id: 7, user_id: 2)
GameUser.create(game_id: 47, user_id: 2)
GameUser.create(game_id: 8, user_id: 2)
GameUser.create(game_id: 46, user_id: 2)
GameUser.create(game_id: 9, user_id: 2)
GameUser.create(game_id: 45, user_id: 1)
GameUser.create(game_id: 10, user_id: 1)
GameUser.create(game_id: 44, user_id: 1)
GameUser.create(game_id: 11, user_id: 1)
GameUser.create(game_id: 43, user_id: 1)

GameUser.create(game_id: 8, user_id: 1)
GameUser.create(game_id: 46, user_id: 1)
GameUser.create(game_id: 12, user_id: 1)
GameUser.create(game_id: 15, user_id: 1)
GameUser.create(game_id: 37, user_id: 1)
GameUser.create(game_id: 21, user_id: 1)
GameUser.create(game_id: 32, user_id: 1)
GameUser.create(game_id: 26, user_id: 1)
GameUser.create(game_id: 53, user_id: 1)
GameUser.create(game_id: 4, user_id: 1)
GameUser.create(game_id: 49, user_id: 1)
GameUser.create(game_id: 9, user_id: 1)
GameUser.create(game_id: 44, user_id: 1)

GameUser.create(game_id: 8, user_id: 2)
GameUser.create(game_id: 46, user_id: 2)
GameUser.create(game_id: 12, user_id: 2)
GameUser.create(game_id: 15, user_id: 2)
GameUser.create(game_id: 37, user_id: 2)
GameUser.create(game_id: 21, user_id: 2)
GameUser.create(game_id: 32, user_id: 2)
GameUser.create(game_id: 26, user_id: 2)
GameUser.create(game_id: 53, user_id: 2)
GameUser.create(game_id: 4, user_id: 2)
GameUser.create(game_id: 49, user_id: 2)
GameUser.create(game_id: 9, user_id: 2)
GameUser.create(game_id: 44, user_id: 2)
